// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_UAHD6LGHwFarH7HMk-QkcGX0Q3BKYa8',
    appId: '1:89170590070:web:77e71b4215c35961866257',
    messagingSenderId: '89170590070',
    projectId: 'flutter-auth-2e03e',
    authDomain: 'flutter-auth-2e03e.firebaseapp.com',
    storageBucket: 'flutter-auth-2e03e.firebasestorage.app',
    measurementId: 'G-DFMB64TJ7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtZ24ZvhZVPewnS3MuS5CjJ7aJ5M1nIdM',
    appId: '1:89170590070:android:b921c21c54311054866257',
    messagingSenderId: '89170590070',
    projectId: 'flutter-auth-2e03e',
    storageBucket: 'flutter-auth-2e03e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKre341rzzdrycuF51XcW9LXdOcBRq8q8',
    appId: '1:89170590070:ios:1fc197a9a5238f2d866257',
    messagingSenderId: '89170590070',
    projectId: 'flutter-auth-2e03e',
    storageBucket: 'flutter-auth-2e03e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKre341rzzdrycuF51XcW9LXdOcBRq8q8',
    appId: '1:89170590070:ios:1fc197a9a5238f2d866257',
    messagingSenderId: '89170590070',
    projectId: 'flutter-auth-2e03e',
    storageBucket: 'flutter-auth-2e03e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_UAHD6LGHwFarH7HMk-QkcGX0Q3BKYa8',
    appId: '1:89170590070:web:0214e8fbba8df4d2866257',
    messagingSenderId: '89170590070',
    projectId: 'flutter-auth-2e03e',
    authDomain: 'flutter-auth-2e03e.firebaseapp.com',
    storageBucket: 'flutter-auth-2e03e.firebasestorage.app',
    measurementId: 'G-S4PX1NPNLF',
  );
}
